version: '3'
services:
  terraform:
    image: "quay.io/azavea/terraform:0.9.1"
    volumes:
      - ./:/usr/local/src
      - ~/.aws:/root/.aws
    environment:
      - TILEJSON_IO_DEBUG=1
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}
      - TILEJSON_IO_SETTINGS_BUCKET=${TILEJSON_IO_SETTINGS_BUCKET:-tilejson-io-production-config-us-east-1}
      - TILEJSON_IO_SITE_BUCKET=${TILEJSON_IO_SITE_BUCKET:-tilejson-io-production-site-us-east-1}
      - GIT_COMMIT=${GIT_COMMIT:-latest}
    working_dir: /usr/local/src
    entrypoint: bash