#!/bin/bash

set -e

if [[ -n "${TILEJSON_IO_DEBUG}" ]]; then
    set -x
fi

function usage() {
    echo -n "Usage: $(basename "$0")

Run project test suite.
"
}

if [ "${BASH_SOURCE[0]}" = "${0}" ]; then
    if [ "${1:-}" = "--help" ]; then
        usage
    else
        # Lint Bash scripts
        if command -v shellcheck; then
            shellcheck scripts/*
        fi

        # Lint JavaScript
        pushd src/app
        yarn test
        popd
    fi
fi
