---
- hosts: all
  become: True

  pre_tasks:
    - name: Update APT cache
      apt:
        update_cache: yes
        cache_valid_time: 3600

  roles:
    - { role: "azavea.nodejs" }
    - { role: "azavea.yarn" }
    - { role: "tilejson.io.shellcheck" }
